### ISSUE TITLE
(Maybe) some typos in lab4

### ISSUE THREAD

**Issue by w568w** [FDUCSLG/OS-2022Fall-Fudan#3]
Hi TAs,

It seems that there are some typos in the lab4. I am not sure whether they have been corrected in this week's lab course.

1. It should be `k->sum = -i - 1` to pass the test:
https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/70f5fe2251625f29bf7b6a0fe8815e5b738151ee/src/test/ipctest.c#L17
2. Will this line assert `msg[i] == -i`?
https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/70f5fe2251625f29bf7b6a0fe8815e5b738151ee/src/test/ipctest.c#L53
3. `sys_msgrcv()` does not set `msgp->mtype` to `found_msg->mtype`, so the former will be rubbish value.
https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/70f5fe2251625f29bf7b6a0fe8815e5b738151ee/src/common/ipc.c#L259

**Comment by chenlidar** [comment]
It's a bug.
Now fixed.

**Comment by w568w** [comment]
Thanks 😂. And a bit more... I would rather append another one to this issue since it is quite trivial.

`mbox_get_clock_rate` is defined as: https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/3caa6b2b2288b15d4c23c4abd9da730637929f48/src/driver/mbox.c#L90

But it is later called like: https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/3caa6b2b2288b15d4c23c4abd9da730637929f48/src/driver/sddef.h#L1088

What is the parameter `MBX_PROP_CLOCK_EMMC` for?

**Comment by maZymaZe** [comment]
legacy code from https://github.com/moizumi99/RPiHaribote/blob/master/haribote/mailbox.c#L70

**Comment by maZymaZe** [comment]
you can remove the unused parameter

**Comment by w568w** [comment]
I see, thanks a lot.
