### ISSUE TITLE
Unexpected behavior when using `_for_in_list` on an empty list

### ISSUE THREAD

**Issue by w568w** [FDUCSLG/OS-2022Fall-Fudan#4]
The macro `_for_in_list` is used to walk through a linked list. 

https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/cfeb7991b139f4af541d8dccf4eca3a6f56bacf5/src/common/list.h#L26

However, it does not check whether `list->next == list` (i.e. the list is empty) when entering the loop, and executes the loop body once with `valptr = list`, which is not expected in most cases.

A possible fix is:
```c
// - walk through the list
#define _for_in_list(valptr, list) \
    for (ListNode* __flag = (list), *valptr = __flag->next; valptr && valptr != __flag; \
         valptr = valptr == __flag ? (void*)0 : valptr->next)
```

I have read the API references and code comments in the repository, none of them mentioning the behavior here. Please correct me if it has been pointed out somewhere.

**Comment by zzzly3** [comment]
`_for_in_list` is designed to walk through a list from the given node, NOT WALK THROUGH A HEADED LIST FROM THE HEAD.

**Comment by w568w** [comment]
> `_for_in_list` is designed to walk through a list from the given node, NOT WALK THROUGH A HEADED LIST FROM THE HEAD.

Then maybe it is better to clarify it in the documentation? Now `_for_in_list` will:

- **Skip the head** in a non-empty headed list;
- **Do not skip the head** in an empty headed list;
- **Skip the current item** in a non-empty headless list;
- **Crash** in an empty headless list. (a.k.a `NULL`)

Is there any consideration to design a macro working like this?

Edit: I cannot find a good implementation, but [Linux](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/list.h?h=linux-2.6.33.y#n367)'s `__list_for_each` seems to deal with this situation.

**Comment by zzzly3** [comment]
It shouldn't skip any nodes... Have you found a bug or misunderstood something?

**Comment by w568w** [comment]
> It shouldn't skip any nodes... Have you found a bug or misunderstood something?

Ohh... I had some misunderstanding here. There is nothing wrong with the macro, then. Thanks!
