### ISSUE TITLE
`console_intr` will never read a `BACKSPACE`

### ISSUE THREAD

**Issue by w568w** [FDUCSLG/OS-2022Fall-Fudan#5]
In lab10, `uart_get_char` returns a `char` ranged in `0xff`:

https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/6c1d233e3b21b4989f0183790f9742e0900bedb3/src/driver/uart.c#L40

whereas `BACKSPACE` defined in `console.c` requires a `0x100`:

https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/6c1d233e3b21b4989f0183790f9742e0900bedb3/src/kernel/console.c#L14

which obviously exceeds the possible output range of the former. 

Should `uart_get_char` rather produce a wide character, i.e. `int`, like the one in xv6?

**Comment by chenlidar** [comment]
感谢！
这里解释一下：
1.define的BACKSPACE是一个用于输出处理的范围外的标识，因为uart_put_char一个BACKSPACE要特殊处理，而不是真实的ascii码，所以用一个范围外的数来做标识
2.uart_get_char读入的backspace的ascii是127
所以返回值用char没有问题，因为不会超过0xff。

**Comment by w568w** [comment]
> define 的 BACKSPACE 是一个用于输出处理的范围外的标识，因为 uart_put_char 一个 BACKSPACE 要特殊处理，而不是真实的 ascii 码，所以用一个范围外的数来做标识

哦 😂 原来是这样，我之前当作某种特殊的 ASCII 码了。感谢，现在理解了 🚀
